### ISSUE TITLE
missing components folder in the stable release 0.9.5-dev

### ISSUE THREAD

**Issue by aad** [orange-cloudfoundry/stratos-ui-cf-packager#1]
Hi Team,

Really nice work, very helpful!

Could you include the `components` into the stable release so that we can check out the release/tag (instead of `master`) & compile the binary by ourselves?

**Comment by gberche-orange** [comment]
@aad would make sense to follow up with the statos team see related https://github.com/SUSE/stratos-ui/issues/1370

**Comment by ArthurHlt** [comment]
Hi sorry for the delay

I have created a new release in 0.9.9 and it's stable with `register-multi-endpoints` component included.
