### ISSUE TITLE
Version 2.4.0 build fails on golang backend 

### ISSUE THREAD

**Issue by gberche-orange** [orange-cloudfoundry/stratos-ui-cf-packager#3]
https://travis-ci.org/orange-cloudfoundry/stratos-ui-cf-packager/builds/528716689 fails with

```
Building backend ...
Building version: 2.4.0
migrator.go:12:2: cannot find package "bitbucket.org/liamstask/goose/lib/goose" in any of:
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/bitbucket.org/liamstask/goose/lib/goose (from $GOROOT)
	/home/travis/gopath/src/bitbucket.org/liamstask/goose/lib/goose (from $GOPATH)
main.go:25:2: cannot find package "github.com/antonlindstrom/pgstore" in any of:
	/home/travis/.gimme/versions/go1.10.linux.amd64/src/github.com/antonlindstrom/pgstore (from $GOROOT)
	/home/travis/gopath/src/github.com/antonlindstrom/pgstore (from $GOPATH)
main.go:26:2: cannot find package "github.com/cf-stratos/mysqlstore" in any of:
[...]
```

Wondering whether this could be linked to https://github.com/golang/go/issues/23950 
   * https://github.com/golang/go/wiki/vgo

https://github.com/cloudfoundry-incubator/stratos/pull/3493 bumped golang to go1.12.4

Current travis builds against

https://github.com/orange-cloudfoundry/stratos-ui-cf-packager/blob/eed2aa77d62201eaf4507df5b964ddc9a36d0d43/.travis.yml#L1-L3

**Comment by ArthurHlt** [comment]
They use vgo now yes, i'm updating to use vgo on this packager

**Comment by ArthurHlt** [comment]
see commit https://github.com/orange-cloudfoundry/stratos-ui-cf-packager/commit/07ce0403af837c9e6fa0bc17999bfa1be44c6bc3 and commit https://github.com/orange-cloudfoundry/stratos-ui-cf-packager/commit/4f647d8ab28af8b79543182ba70f8fbce608621a 

Version 2.4.0 has been built and can be found here https://github.com/orange-cloudfoundry/stratos-ui-cf-packager/releases/tag/2.4.0
